create extension if not exists pgcrypto with schema extensions;

create table if not exists public.membership_payment_resume_tokens (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  member_id uuid not null references public.members(id) on delete cascade,
  profile_registration_id uuid references public.profile_registrations(id) on delete set null,
  email text not null,
  email_norm text generated always as (lower(nullif(btrim(email), ''))) stored,
  locale text not null default 'en',
  source text not null default 'manual_request',
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  constraint membership_payment_resume_tokens_locale_check
    check (locale in ('en', 'es')),
  constraint membership_payment_resume_tokens_source_check
    check (source in ('loops_workflow', 'manual_request'))
);

create index if not exists membership_payment_resume_tokens_member_id_idx
  on public.membership_payment_resume_tokens (member_id);

create index if not exists membership_payment_resume_tokens_expires_idx
  on public.membership_payment_resume_tokens (expires_at)
  where used_at is null;

create table if not exists public.membership_payment_resume_sessions (
  id uuid primary key default gen_random_uuid(),
  session_hash text not null unique,
  token_id uuid references public.membership_payment_resume_tokens(id) on delete set null,
  member_id uuid not null references public.members(id) on delete cascade,
  email text not null,
  email_norm text generated always as (lower(nullif(btrim(email), ''))) stored,
  locale text not null default 'en',
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint membership_payment_resume_sessions_locale_check
    check (locale in ('en', 'es'))
);

create index if not exists membership_payment_resume_sessions_expires_idx
  on public.membership_payment_resume_sessions (expires_at);

create index if not exists membership_payment_resume_sessions_member_id_idx
  on public.membership_payment_resume_sessions (member_id);

create table if not exists public.profile_submissions (
  id text primary key,
  style text,
  locale text not null default 'en',
  status text not null default 'started',
  current_page integer,
  current_section text,
  answers_json jsonb not null default '{}'::jsonb,
  feedback_json jsonb not null default '{}'::jsonb,
  timing_json jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  last_seen_at timestamptz not null default now(),
  completed_profile_at timestamptz,
  submitted_feedback_at timestamptz,
  google_submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profile_submissions_locale_check
    check (locale in ('en', 'es'))
);

create index if not exists profile_submissions_status_idx
  on public.profile_submissions (status);

create index if not exists profile_submissions_last_seen_at_idx
  on public.profile_submissions (last_seen_at);

create index if not exists profile_submissions_locale_idx
  on public.profile_submissions (locale);

create table if not exists public.profile_events (
  id bigint generated by default as identity primary key,
  legacy_d1_event_id integer unique,
  submission_id text not null references public.profile_submissions(id) on delete cascade,
  event_type text not null,
  locale text not null default 'en',
  section_id text,
  page_index integer,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint profile_events_locale_check
    check (locale in ('en', 'es'))
);

create index if not exists profile_events_submission_id_idx
  on public.profile_events (submission_id);

create index if not exists profile_events_created_at_idx
  on public.profile_events (created_at);

create index if not exists profile_events_legacy_d1_event_id_idx
  on public.profile_events (legacy_d1_event_id)
  where legacy_d1_event_id is not null;

create index if not exists profile_events_locale_idx
  on public.profile_events (locale);

alter table public.membership_payment_resume_tokens enable row level security;
alter table public.membership_payment_resume_sessions enable row level security;
alter table public.profile_submissions enable row level security;
alter table public.profile_events enable row level security;

revoke all on table public.membership_payment_resume_tokens from anon, authenticated;
revoke all on table public.membership_payment_resume_sessions from anon, authenticated;
revoke all on table public.profile_submissions from anon, authenticated;
revoke all on table public.profile_events from anon, authenticated;

grant all on table public.membership_payment_resume_tokens to service_role;
grant all on table public.membership_payment_resume_sessions to service_role;
grant all on table public.profile_submissions to service_role;
grant all on table public.profile_events to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.hash_payment_resume_secret(p_value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select encode(extensions.digest(coalesce(p_value, ''), 'sha256'), 'hex');
$$;

create or replace function public.generate_payment_resume_secret()
returns text
language sql
volatile
set search_path = ''
as $$
  select replace(extensions.gen_random_uuid()::text, '-', '') || replace(extensions.gen_random_uuid()::text, '-', '');
$$;

create or replace function public.ensure_member_for_submitted_story(
  p_registration_id uuid,
  p_delay_minutes integer default 15
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  registration_record public.profile_registrations%rowtype;
  member_record public.members%rowtype;
  member_id uuid;
  current_time timestamptz := now();
begin
  select *
    into registration_record
  from public.profile_registrations
  where id = p_registration_id
    and status = 'submitted';

  if registration_record.id is null then
    raise exception 'Submitted story registration was not found.'
      using errcode = 'P0002';
  end if;

  if registration_record.contact_email_norm is null then
    raise exception 'Submitted story registration does not have a valid email.'
      using errcode = '22023';
  end if;

  member_id := public.ensure_member_for_email(registration_record.contact_email, current_time);

  select *
    into member_record
  from public.members
  where id = member_id;

  if member_record.membership_status = 'active' then
    return jsonb_build_object(
      'ok', true,
      'memberId', member_id,
      'registrationId', registration_record.id,
      'email', registration_record.contact_email,
      'locale', registration_record.locale,
      'firstName', nullif(registration_record.profile_json ->> 'profile.first_name', ''),
      'submittedAt', registration_record.submitted_at,
      'membershipStatus', member_record.membership_status,
      'paymentRequired', false
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'memberId', member_id,
    'registrationId', registration_record.id,
    'email', registration_record.contact_email,
    'locale', registration_record.locale,
    'firstName', nullif(registration_record.profile_json ->> 'profile.first_name', ''),
    'submittedAt', registration_record.submitted_at,
    'membershipStatus', member_record.membership_status,
    'paymentRequired', true
  );
end;
$$;

create or replace function public.create_membership_payment_resume_token_for_email(
  p_email text,
  p_token_ttl_minutes integer default 30,
  p_source text default 'manual_request'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  cleaned_email text := lower(nullif(btrim(p_email), ''));
  registration_record public.profile_registrations%rowtype;
  member_record public.members%rowtype;
  member_id uuid;
  token_id uuid;
  generated_token text;
  token_expires_at timestamptz;
  current_time timestamptz := now();
  ttl_minutes integer := greatest(1, least(coalesce(p_token_ttl_minutes, 30), 1440));
  clean_source text := case
    when p_source = 'loops_workflow' then 'loops_workflow'
    else 'manual_request'
  end;
begin
  if cleaned_email is null or cleaned_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    return jsonb_build_object('ok', false);
  end if;

  select *
    into registration_record
  from public.profile_registrations
  where contact_email_norm = cleaned_email
    and status = 'submitted'
  order by submitted_at desc nulls last, updated_at desc
  limit 1;

  if registration_record.id is null then
    return jsonb_build_object('ok', false);
  end if;

  member_id := public.ensure_member_for_email(registration_record.contact_email, current_time);

  select *
    into member_record
  from public.members
  where id = member_id;

  if member_record.membership_status <> 'pending' then
    return jsonb_build_object('ok', false);
  end if;

  generated_token := public.generate_payment_resume_secret();
  token_expires_at := current_time + make_interval(mins => ttl_minutes);

  insert into public.membership_payment_resume_tokens (
    token_hash,
    member_id,
    profile_registration_id,
    email,
    locale,
    source,
    expires_at,
    created_at
  )
  values (
    public.hash_payment_resume_secret(generated_token),
    member_id,
    registration_record.id,
    registration_record.contact_email,
    registration_record.locale,
    clean_source,
    token_expires_at,
    current_time
  )
  returning id into token_id;

  return jsonb_build_object(
    'ok', true,
    'tokenId', token_id,
    'token', generated_token,
    'expiresAt', token_expires_at,
    'memberId', member_id,
    'registrationId', registration_record.id,
    'email', registration_record.contact_email,
    'locale', registration_record.locale,
    'firstName', nullif(registration_record.profile_json ->> 'profile.first_name', '')
  );
end;
$$;

create or replace function public.claim_membership_payment_resume_token(
  p_token text,
  p_session_ttl_minutes integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  token_record public.membership_payment_resume_tokens%rowtype;
  member_record public.members%rowtype;
  session_token text;
  session_expires_at timestamptz;
  current_time timestamptz := now();
  ttl_minutes integer := greatest(1, least(coalesce(p_session_ttl_minutes, 30), 1440));
begin
  if nullif(btrim(p_token), '') is null then
    return jsonb_build_object('ok', false);
  end if;

  select *
    into token_record
  from public.membership_payment_resume_tokens
  where token_hash = public.hash_payment_resume_secret(p_token)
    and used_at is null
    and expires_at > current_time
  for update;

  if token_record.id is null then
    return jsonb_build_object('ok', false);
  end if;

  select *
    into member_record
  from public.members
  where id = token_record.member_id;

  update public.membership_payment_resume_tokens
    set used_at = current_time
  where id = token_record.id;

  if member_record.id is null or member_record.membership_status <> 'pending' then
    return jsonb_build_object('ok', false);
  end if;

  session_token := public.generate_payment_resume_secret();
  session_expires_at := current_time + make_interval(mins => ttl_minutes);

  insert into public.membership_payment_resume_sessions (
    session_hash,
    token_id,
    member_id,
    email,
    locale,
    expires_at,
    created_at
  )
  values (
    public.hash_payment_resume_secret(session_token),
    token_record.id,
    token_record.member_id,
    token_record.email,
    token_record.locale,
    session_expires_at,
    current_time
  );

  return jsonb_build_object(
    'ok', true,
    'sessionToken', session_token,
    'maxAgeSeconds', ttl_minutes * 60,
    'memberId', token_record.member_id,
    'email', token_record.email,
    'locale', token_record.locale,
    'expiresAt', session_expires_at
  );
end;
$$;

create or replace function public.resolve_membership_payment_resume_session(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  session_record public.membership_payment_resume_sessions%rowtype;
  member_status text;
begin
  if nullif(btrim(p_session_token), '') is null then
    return jsonb_build_object('ok', false);
  end if;

  select *
    into session_record
  from public.membership_payment_resume_sessions
  where session_hash = public.hash_payment_resume_secret(p_session_token)
    and expires_at > now();

  if session_record.id is null then
    return jsonb_build_object('ok', false);
  end if;

  select membership_status
    into member_status
  from public.members
  where id = session_record.member_id;

  if member_status <> 'pending' then
    return jsonb_build_object('ok', false);
  end if;

  return jsonb_build_object(
    'ok', true,
    'memberId', session_record.member_id,
    'email', session_record.email,
    'locale', session_record.locale,
    'expiresAt', session_record.expires_at
  );
end;
$$;

create or replace function public.record_profile_progress(
  p_submission_id text,
  p_event_type text,
  p_status text,
  p_style text default null,
  p_locale text default 'en',
  p_current_page integer default null,
  p_current_section text default null,
  p_answers jsonb default '{}'::jsonb,
  p_feedback jsonb default '{}'::jsonb,
  p_timing jsonb default '{}'::jsonb,
  p_payload jsonb default '{}'::jsonb,
  p_completed_profile_at timestamptz default null,
  p_submitted_feedback_at timestamptz default null,
  p_now timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  clean_locale text := case when lower(coalesce(p_locale, 'en')) = 'es' then 'es' else 'en' end;
begin
  insert into public.profile_submissions (
    id,
    style,
    locale,
    status,
    current_page,
    current_section,
    answers_json,
    feedback_json,
    timing_json,
    started_at,
    last_seen_at,
    completed_profile_at,
    submitted_feedback_at,
    created_at,
    updated_at
  )
  values (
    p_submission_id,
    nullif(btrim(p_style), ''),
    clean_locale,
    p_status,
    p_current_page,
    nullif(btrim(p_current_section), ''),
    coalesce(p_answers, '{}'::jsonb),
    coalesce(p_feedback, '{}'::jsonb),
    coalesce(p_timing, '{}'::jsonb),
    p_now,
    p_now,
    p_completed_profile_at,
    p_submitted_feedback_at,
    p_now,
    p_now
  )
  on conflict (id) do update
    set style = excluded.style,
        locale = excluded.locale,
        status = excluded.status,
        current_page = excluded.current_page,
        current_section = excluded.current_section,
        answers_json = excluded.answers_json,
        feedback_json = excluded.feedback_json,
        timing_json = excluded.timing_json,
        last_seen_at = excluded.last_seen_at,
        completed_profile_at = coalesce(public.profile_submissions.completed_profile_at, excluded.completed_profile_at),
        submitted_feedback_at = coalesce(public.profile_submissions.submitted_feedback_at, excluded.submitted_feedback_at),
        updated_at = excluded.updated_at;

  insert into public.profile_events (
    submission_id,
    event_type,
    locale,
    section_id,
    page_index,
    payload_json,
    created_at
  )
  values (
    p_submission_id,
    p_event_type,
    clean_locale,
    nullif(btrim(p_current_section), ''),
    p_current_page,
    coalesce(p_payload, '{}'::jsonb),
    p_now
  );

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.mark_profile_google_submitted(
  p_submission_id text,
  p_submitted_at timestamptz,
  p_status text
)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.profile_submissions
    set google_submitted_at = p_submitted_at,
        status = p_status,
        last_seen_at = p_submitted_at,
        updated_at = now()
  where id = p_submission_id;
$$;

revoke all on function public.hash_payment_resume_secret(text) from public, anon, authenticated;
revoke all on function public.generate_payment_resume_secret() from public, anon, authenticated;
revoke all on function public.ensure_member_for_submitted_story(uuid, integer) from public, anon, authenticated;
revoke all on function public.create_membership_payment_resume_token_for_email(text, integer, text) from public, anon, authenticated;
revoke all on function public.claim_membership_payment_resume_token(text, integer) from public, anon, authenticated;
revoke all on function public.resolve_membership_payment_resume_session(text) from public, anon, authenticated;
revoke all on function public.record_profile_progress(text, text, text, text, text, integer, text, jsonb, jsonb, jsonb, jsonb, timestamptz, timestamptz, timestamptz) from public, anon, authenticated;
revoke all on function public.mark_profile_google_submitted(text, timestamptz, text) from public, anon, authenticated;

grant execute on function public.ensure_member_for_submitted_story(uuid, integer) to service_role;
grant execute on function public.create_membership_payment_resume_token_for_email(text, integer, text) to service_role;
grant execute on function public.claim_membership_payment_resume_token(text, integer) to service_role;
grant execute on function public.resolve_membership_payment_resume_session(text) to service_role;
grant execute on function public.record_profile_progress(text, text, text, text, text, integer, text, jsonb, jsonb, jsonb, jsonb, timestamptz, timestamptz, timestamptz) to service_role;
grant execute on function public.mark_profile_google_submitted(text, timestamptz, text) to service_role;
